- ignore:
    name: "Unused LANGUAGE pragma"
    hint: "TemplateHaskell"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use <$>"
- ignore:
    name: "Use const"
- ignore:
    name: "Redundant bracket"
