name: Build and Upload Artifact

on:
  workflow_dispatch:
    inputs:
      partner_chains_smart_contracts_sha:
        description: "partner-chains-smart-contracts commit SHA or branch to build from"
      partner-chains-smart-contracts-tag:
        description: "partner-chains-smart-contract release tag to append to artifact name (optional)"
        required: false

jobs:
  partner-chains-smart-contracts-build:
    runs-on: [self-hosted, nixos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.partner_chains_smart_contracts_sha }}

      - name: Build
        run: nix build ./#sidechain-release-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: partner-chains-smart-contracts
          path: result/release.zip

  partner-chains-smart-contracts-process:
    runs-on: ubuntu-latest
    needs: partner-chains-smart-contracts-build
    steps:
      - name: Set filename variables
        id: set-filenames
        run: |
          if [ -n "${{ github.event.inputs.partner-chains-smart-contracts-tag }}" ]; then
            echo "SIDECHAIN_MAIN_CLI=sidechain-main-cli-${{ github.event.inputs.partner-chains-smart-contracts-tag }}" >> $GITHUB_ENV
          else
            echo "SIDECHAIN_MAIN_CLI=sidechain-main-cli" >> $GITHUB_ENV
          fi
          
      - name: Download release.zip
        uses: actions/download-artifact@v4
        with:
          name: partner-chains-smart-contracts
          path: ./artifact

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: partner-chains-smart-contracts
  
      - name: Unzip release.zip
        run: |
          mkdir -p artifact/unzipped
          unzip artifact/release.zip -d artifact/unzipped
          
      - name: Rename sidechain-cli to sidechain-main-cli
        run: |
          mv artifact/unzipped/sidechain-cli artifact/unzipped/sidechain-main-cli
  
      - name: Upload Renamed Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SIDECHAIN_MAIN_CLI }}
          path: artifact/unzipped/
