name: "Partner Chains Smart Contracts CI"
on:
  pull_request:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  build-x64-linux:
    permissions:
      id-token: write
      contents: read
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Cache Cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/state/cabal/store
            onchain/dist-newstyle
          key: cabal-${{ runner.os }}-${{ hashFiles('onchain/**/*.cabal', 'onchain/cabal.project', 'onchain/cabal.project.freeze') }}
          restore-keys: |
            cabal-${{ runner.os }}-

      - name: Add signing key for nix
        run: echo "${{ secrets.NIX_SIGNING_KEY }}" > "${{ runner.temp }}/nix-key"

      - name: Lint sources
        run: |
          nix flake check

      - name: Build onchain
        run: |
          cd onchain
          nix develop --command "make"

      - name: Build raw scripts crates
        run: |
          cd raw-scripts
          nix develop --command "make"
          cd ..
          cd raw-scripts-traced
          nix develop --command "make"
