name: Build, Release, and Publish

on:
  workflow_dispatch:
    inputs:
      revision:
        description: "Git Revision to release"
        required: true
      release-version:
        description: "Specify the version number"
        required: true
env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:

  partner-chains-smart-contracts-process:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    outputs:
      pc_contracts_cli: ${{ steps.set_filename_vars_and_rename.outputs.pc_contracts_cli }}
    steps:
      - name: Acquire AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Download artifact from S3
        run: |
          aws s3 cp "s3://pcsc-bucket/${{ github.event.inputs.revision }}.zip" ./pc-contracts-cli-v${{ github.event.inputs.release-version }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ""
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./pc-contracts-cli-v${{ github.event.inputs.release-version }}.zip
          name: "v${{ github.event.inputs.release-version }}"
